============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/stidsem4/iut/2021/controle/kathushna.ambigainathan/c16_03
collected 7 items

test_16_03.py F.FFFFF                                                    [100%]

=================================== FAILURES ===================================
_____________________________ Test1603sute.test_10 _____________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
>           from .main  import Note

test_16_03.py:94: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    note1 = ('eleve1', 'math', 13)
    note2 = ('eleve1', 'physique', 15)
    note3 = ('eleve1', 'math', 13)
    note4 = ('eleve1', 'eco', 12)
    note5 = ('eleve1', 'eco', 13)
    note6 = ('eleve1', 'math', 12)
    note7 = ('eleve2', 'math', 13)
    note8 = ('eleve2', 'math', 14)
    
    notes = [note1, note2, note3, note4, note5, note6,note7,note8]
    
    # Question 4
    #a/ calculez la moyenne de eleve1
    
    print(notes[0][0])
    print(len(note2))
    
    def moyenne(liste):
      valeurs = 0
      for i in range(len(liste)):
          valeurs = valeurs + liste[i][2]
          moyenne = valeurs/len(liste)
      return(moyenne)
    listes_elev1 =  [note1, note2, note3, note4, note5, note6]
    print("la moyenne de l'élève 1",moyenne(listes_elev1))
    
    # b/ calculez la moyenne de eleve1 en maths
    
    liste_elev1_maths = [note1, note3, note6]
    print("la moyenne de l'élève 1 en maths", moyenne(liste_elev1_maths))
    
    
    #c /
>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]

main.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <tuple_iterator object at 0x7f231910e3d0>

>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
E   TypeError: 'bool' object is not iterable

main.py:34: TypeError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
>          assert False
E          AssertionError: assert False

test_16_03.py:96: AssertionError
----------------------------- Captured stdout call -----------------------------
eleve1
3
la moyenne de l'élève 1 13.0
la moyenne de l'élève 1 en maths 12.666666666666666
_____________________________ Test1603sute.test_4 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
>           from main import moyenne_tuples
E           ModuleNotFoundError: No module named 'main'

test_16_03.py:16: ModuleNotFoundError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
            from main import moyenne_tuples
        except ImportError:
            try:
>               from .main import moyenne_tuple as moyenne_tuples

test_16_03.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
main.py:34: in <module>
    moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <tuple_iterator object at 0x7f23191ae940>

>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
E   TypeError: 'bool' object is not iterable

main.py:34: TypeError
----------------------------- Captured stdout call -----------------------------
eleve1
3
la moyenne de l'élève 1 13.0
la moyenne de l'élève 1 en maths 12.666666666666666
_____________________________ Test1603sute.test_5 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_5>

    def test_5(self):
        try:
>           from .main  import Note, onotes

test_16_03.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    note1 = ('eleve1', 'math', 13)
    note2 = ('eleve1', 'physique', 15)
    note3 = ('eleve1', 'math', 13)
    note4 = ('eleve1', 'eco', 12)
    note5 = ('eleve1', 'eco', 13)
    note6 = ('eleve1', 'math', 12)
    note7 = ('eleve2', 'math', 13)
    note8 = ('eleve2', 'math', 14)
    
    notes = [note1, note2, note3, note4, note5, note6,note7,note8]
    
    # Question 4
    #a/ calculez la moyenne de eleve1
    
    print(notes[0][0])
    print(len(note2))
    
    def moyenne(liste):
      valeurs = 0
      for i in range(len(liste)):
          valeurs = valeurs + liste[i][2]
          moyenne = valeurs/len(liste)
      return(moyenne)
    listes_elev1 =  [note1, note2, note3, note4, note5, note6]
    print("la moyenne de l'élève 1",moyenne(listes_elev1))
    
    # b/ calculez la moyenne de eleve1 en maths
    
    liste_elev1_maths = [note1, note3, note6]
    print("la moyenne de l'élève 1 en maths", moyenne(liste_elev1_maths))
    
    
    #c /
>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]

main.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <tuple_iterator object at 0x7f23191e3220>

>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
E   TypeError: 'bool' object is not iterable

main.py:34: TypeError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_5>

    def test_5(self):
        try:
            from .main  import Note, onotes
        except:
>           assert False
E           AssertionError: assert False

test_16_03.py:35: AssertionError
----------------------------- Captured stdout call -----------------------------
eleve1
3
la moyenne de l'élève 1 13.0
la moyenne de l'élève 1 en maths 12.666666666666666
_____________________________ Test1603sute.test_6 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_6>

    def test_6(self):
>       from .main import Note, onotes

test_16_03.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
main.py:34: in <module>
    moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <tuple_iterator object at 0x7f23191a08e0>

>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
E   TypeError: 'bool' object is not iterable

main.py:34: TypeError
----------------------------- Captured stdout call -----------------------------
eleve1
3
la moyenne de l'élève 1 13.0
la moyenne de l'élève 1 en maths 12.666666666666666
_____________________________ Test1603sute.test_8 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_8>

    def test_8(self):
        try:
>           from .main import Note

test_16_03.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
main.py:34: in <module>
    moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <tuple_iterator object at 0x7f23191ad5b0>

>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
E   TypeError: 'bool' object is not iterable

main.py:34: TypeError
----------------------------- Captured stdout call -----------------------------
eleve1
3
la moyenne de l'élève 1 13.0
la moyenne de l'élève 1 en maths 12.666666666666666
_____________________________ Test1603sute.test_9 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_9>

    def test_9(self):
        try:
>           from .main  import Note

test_16_03.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    note1 = ('eleve1', 'math', 13)
    note2 = ('eleve1', 'physique', 15)
    note3 = ('eleve1', 'math', 13)
    note4 = ('eleve1', 'eco', 12)
    note5 = ('eleve1', 'eco', 13)
    note6 = ('eleve1', 'math', 12)
    note7 = ('eleve2', 'math', 13)
    note8 = ('eleve2', 'math', 14)
    
    notes = [note1, note2, note3, note4, note5, note6,note7,note8]
    
    # Question 4
    #a/ calculez la moyenne de eleve1
    
    print(notes[0][0])
    print(len(note2))
    
    def moyenne(liste):
      valeurs = 0
      for i in range(len(liste)):
          valeurs = valeurs + liste[i][2]
          moyenne = valeurs/len(liste)
      return(moyenne)
    listes_elev1 =  [note1, note2, note3, note4, note5, note6]
    print("la moyenne de l'élève 1",moyenne(listes_elev1))
    
    # b/ calculez la moyenne de eleve1 en maths
    
    liste_elev1_maths = [note1, note3, note6]
    print("la moyenne de l'élève 1 en maths", moyenne(liste_elev1_maths))
    
    
    #c /
>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]

main.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <tuple_iterator object at 0x7f23191ae2b0>

>   moyenne_tuples = [(x,y) for x in ['eleve1','eleve2'] for y in ['math','physique','eco'] in notes]
E   TypeError: 'bool' object is not iterable

main.py:34: TypeError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_9>

    def test_9(self):
        try:
            from .main  import Note
        except:
>          assert False
E          AssertionError: assert False

test_16_03.py:89: AssertionError
----------------------------- Captured stdout call -----------------------------
eleve1
3
la moyenne de l'élève 1 13.0
la moyenne de l'élève 1 en maths 12.666666666666666
=========================== short test summary info ============================
FAILED test_16_03.py::Test1603sute::test_10 - AssertionError: assert False
FAILED test_16_03.py::Test1603sute::test_4 - TypeError: 'bool' object is not ...
FAILED test_16_03.py::Test1603sute::test_5 - AssertionError: assert False
FAILED test_16_03.py::Test1603sute::test_6 - TypeError: 'bool' object is not ...
FAILED test_16_03.py::Test1603sute::test_8 - TypeError: 'bool' object is not ...
FAILED test_16_03.py::Test1603sute::test_9 - AssertionError: assert False
========================= 6 failed, 1 passed in 0.11s ==========================
